### ISSUE TITLE
Using "private" instead of "reveal"

### ISSUE THREAD

**Issue by artginzburg** [mvila/npm-addict#33]
As I'm still not seeing NPM accept the `"reveal": true` property (https://npmaddict.com/#/faq), I suggest to use `"private": false` (https://docs.npmjs.com/cli/v7/configuring-npm/package-json#private) instead.

The logic of npm-addict can stay similar:
> New packages with at least 5 GitHub stars or the `private` property set to `false` in `package.json`

Another reason we may want to implement that is the conflict of properties.
e.g. What happens if a package has both `"private": true` and `"reveal": true`?

**Comment by mvila** [comment]
Thanks @artginzburg, it's an interesting idea.

What you propose would be like having a tristate attribute:

1. `"private": true`: The package is not published on npm.
2. `"private": false`: The package is published on npm and npm addict.
3. The `"private"` attribute is missing or set to `undefined`: The package is published on npm and _potentially_ on npm addict depending on the number of GitHub stars.

The problem is that the second and third options (`false` or `undefined`) are intuitively equivalent in many people's minds, and I'm afraid that this will bring confusion.
